### ISSUE TITLE
Installation fails with `pipenv install jazzit`

### ISSUE THREAD

**Issue by mrlubos** [Sangarshanan/jazzit#17]
Hey! I want to try out this script, but sadly it fails when running `pipenv install jazzit` with the following message.

```
Installing jazzit…
Error:  An error occurred while installing jazzit!
Error text: Collecting jazzit
  Using cached jazzit-0.2.0.tar.gz (3.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: /Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/bin/python /Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/2l/wpk3nrwx0fqfb35jyjssgy1w0000gn/T/pip-build-env-c9x3093u/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --pre -- 'setuptools >= 40.6.0' wheel
       cwd: None
  Complete output (44 lines):
  Traceback (most recent call last):
    File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.package_finder import PackageFinder
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
      from pip._internal.index.collector import parse_links
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
      from . import utils
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import read_text
    File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/bin/python /Users/mrlubos/.local/share/virtualenvs/api-T1wVW5XM/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/2l/wpk3nrwx0fqfb35jyjssgy1w0000gn/T/pip-build-env-c9x3093u/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --pre -- 'setuptools >= 40.6.0' wheel Check the logs for full command output.

✘ Installation Failed 
```

I have also tried putting it in `Pipfile` and then running `pipenv install` which produces the following error.

```
An error occurred while installing jazzit==0.2.0 --hash=sha256:90b6d1d8d06ce2e47eac2d395869352d59f8eb7fcce5d77f3ecf2f9a035a542a! Will try again.
Installing initially failed dependencies…
[InstallError]:   File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/cli/command.py", line 232, in install
[InstallError]:       retcode = do_install(
[InstallError]:   File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/core.py", line 2051, in do_install
[InstallError]:       do_init(
[InstallError]:   File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/core.py", line 1306, in do_init
[InstallError]:       do_install_dependencies(
[InstallError]:   File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/core.py", line 900, in do_install_dependencies
[InstallError]:       batch_install(
[InstallError]:   File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: Collecting jazzit==0.2.0
[pipenv.exceptions.InstallError]:   Using cached jazzit-0.2.0.tar.gz (3.1 MB)
[pipenv.exceptions.InstallError]: ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml
ERROR: Couldn't install package: jazzit
```

Are you able to advise what am I doing wrong please? The install works with `pip` from Terminal, but I wanted to add this to an existing project.

**Comment by Sangarshanan** [comment]
The first issue you facing seems to be the same as https://github.com/ethereum/eth-abi/issues/131 
you could try to `pip uninstall typing` from your trace I see you are on python3.7 so typing is already in the standard library

The second issue is because of the `build-backend`, I am guessing adding a flag to your Pipefile might help `jazzit = { version="*", pip_options=['--no-use-pep517'] }` but I can't really reproduce locally so if this doesn't work it would be golden if you could share your Pipfile and also the versions of your pipenv & pip

Thanks for trying out the package : )
